# source('0_0_get_segments_elevation.R')
# source('0_1_initiate_ibwt_segments.R')
# source('0_2_place_aqueducts_and_tunnels.R')
# source('0_3_0_get_information_sections.R')
# source('0_3_1_get_information_segments.R')
# source('0_3_2_get_information_bypass.R')


source('1_0_1_filter_timeseries.R')
source('1_2_0_add_reservoir_information.R')
source('1_2_1_bias_correction_factors.R')
source('1_2_2_bias_correction_discharge.R')
source('1_3_0_get_info_hydropower.R')
source('1_3_1_get_info_pumping_lift.R')
source('1_3_2_get_info_bypass_segments.R')
source('1_3_3_get_info_discharge_only.R')
source('2_0_energy_production.R')
source('2_1_energy_consumption.R')
source('2_2_energy_savings.R')
source('2_3_discharge_only.R')
source('3_0_energy_bugdet.R')
source('3_1_discharge_by_intake_type.R')
source('3_2_country_level_ratios.R')
source('4_validation_hydropower.R')
source('5_paper_summaries.R')